version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-tier
  myapp:
    image: 'my-go-app:latest'
    container_name: my-go-app
    ports:
      - "8080:8081"
    networks:
      - app-tier
