apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-service
    tier: data
  ports:
    - name: redis-service
      protocol: TCP
      port: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web-service
    tier: data
  ports:
    - port: 80
      targetPort: 8081
